---
name: Frontend Bug Report
about: Report a bug or issue with the frontend
title: "[Bug] "
labels: ["bug"]
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        ## Frontend Bug Report

        Thanks for reporting this issue! Please provide the details below to help us fix it quickly.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Briefly describe what's not working.
      placeholder: e.g., "Button not responding to clicks"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to...
        2. Click on...
        3. Observe...
    validations:
      required: true

  - type: input
    id: affected
    attributes:
      label: Affected Page/Component
      description: Where does the issue occur?
      placeholder: e.g., "/search page", "Hero component"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: e.g., "The button should submit the form"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens instead?
      placeholder: e.g., "The button does nothing when clicked"
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser & OS
      description: "Optional: What browser and OS are you using?"
      placeholder: e.g., "Chrome 120 on Windows 11"
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Code
      description: "Optional: Add screenshots or code snippets if helpful."
      placeholder: "Drag and drop images or paste code here."
    validations:
      required: false
